# Render.com deployment configuration for SageForge
services:
  - type: web
    name: sageforge-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --host 0.0.0.0 --port $PORT --worker-class uvicorn.workers.UvicornWorker --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ANGEL_ONE_API_KEY
        sync: false  # Set this in Render dashboard
      - key: ANGEL_ONE_CLIENT_ID
        sync: false  # Set this in Render dashboard  
      - key: ANGEL_ONE_PASSWORD
        sync: false  # Set this in Render dashboard
      - key: ANGEL_ONE_TOTP_SECRET
        sync: false  # Set this in Render dashboard
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: sageforge-api
          property: port

  - type: static
    name: sageforge-frontend
    staticPublishPath: ./frontend
    buildCommand: echo "Static files ready"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html