# Render deployment - Python 3.11 forced
services:
  - type: web
    name: sageforge-api
    env: python
    plan: starter
    runtime: python-3.11.6
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel &&
      pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: ANGEL_ONE_API_KEY
        sync: false
      - key: ANGEL_ONE_CLIENT_ID
        sync: false  
      - key: ANGEL_ONE_PASSWORD
        sync: false
      - key: ANGEL_ONE_TOTP_SECRET
        sync: false
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0