services:
  - type: web
    name: sageforge-backtesting
    env: python
    runtime: python-3.11.9
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ANGEL_ONE_API_KEY
        sync: false
      - key: ANGEL_ONE_CLIENT_ID
        sync: false
      - key: ANGEL_ONE_PASSWORD
        sync: false
      - key: ANGEL_ONE_TOTP_SECRET
        sync: false
